version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5050:5000"
    environment:
      FLASK_APP: inf349
      FLASK_RUN_PORT: 5000
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: pass
      DB_PORT: 5432
      DB_NAME: api8inf349
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    container_name: flask_worker
    command: flask worker
    environment:
      FLASK_APP: inf349
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: pass
      DB_PORT: 5432
      DB_NAME: api8inf349
      REDIS_URL: redis://redis:6379
    depends_on:
      - web
      - redis
      - postgres

  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: api8inf349
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:5
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
